-- !!! THIS PROCESS REQUIRES A USER WITH ACCOUNTADMIN ROLE !!!
-- Cloning objects to grant access to specific views in SNOWFLAKE.ACCOUNT_USAGE
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_READ;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_READ.ACCOUNT_USAGE;
CREATE OR REPLACE VIEW SNOWFLAKE_READ.ACCOUNT_USAGE.TABLES COPY GRANTS AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES;
CREATE OR REPLACE VIEW SNOWFLAKE_READ.ACCOUNT_USAGE.COLUMNS COPY GRANTS AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS;
CREATE OR REPLACE VIEW SNOWFLAKE_READ.ACCOUNT_USAGE.COPY_HISTORY COPY GRANTS AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY;
CREATE OR REPLACE VIEW SNOWFLAKE_READ.ACCOUNT_USAGE.ACCESS_HISTORY COPY GRANTS AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY;
CREATE OR REPLACE VIEW SNOWFLAKE_READ.ACCOUNT_USAGE.QUERY_HISTORY COPY GRANTS AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;
CREATE OR REPLACE VIEW SNOWFLAKE_READ.ACCOUNT_USAGE.OBJECT_DEPENDENCIES COPY GRANTS AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES;

-- Creating role and granting access
SET V_ROLE = 'DATA_GOVERNANCE';
SET V_DATABASE = 'SNOWFLAKE_READ';
CREATE ROLE IF NOT EXISTS IDENTIFIER($V_ROLE);
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE IDENTIFIER($V_ROLE);
GRANT USAGE ON DATABASE IDENTIFIER($V_DATABASE) TO ROLE IDENTIFIER($V_ROLE);
USE IDENTIFIER($V_DATABASE);
GRANT USAGE ON SCHEMA ACCOUNT_USAGE TO ROLE IDENTIFIER($V_ROLE);
GRANT SELECT ON ACCOUNT_USAGE.TABLES TO ROLE IDENTIFIER($V_ROLE);
GRANT SELECT ON ACCOUNT_USAGE.COLUMNS TO ROLE IDENTIFIER($V_ROLE);
GRANT SELECT ON ACCOUNT_USAGE.COPY_HISTORY TO ROLE IDENTIFIER($V_ROLE);
GRANT SELECT ON ACCOUNT_USAGE.ACCESS_HISTORY TO ROLE IDENTIFIER($V_ROLE);
GRANT SELECT ON ACCOUNT_USAGE.QUERY_HISTORY TO ROLE IDENTIFIER($V_ROLE);
GRANT SELECT ON ACCOUNT_USAGE.OBJECT_DEPENDENCIES TO ROLE IDENTIFIER($V_ROLE);

-- Creating user (Optional) and granting DATA_GOVERNANCE role
SET V_USER = 'USER_READ';
-- CREATE USER IDENTIFIER($V_USER) PASSWORD='<password>' DEFAULT_ROLE = DATA_GOVERNANCE;
GRANT ROLE DATA_GOVERNANCE TO USER IDENTIFIER($V_USER);
