[tool.poetry]
name = "faker-sample"
version = "0.1.0"
description = ""
authors = ["Arthur Ribeiro"]

[tool.poetry.dependencies]
python = "^3.10"
faker = "^19.3.0"
pandas = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
